# Generated by Django 5.1.2 on 2024-11-06 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
