# Generated by Django 5.1.2 on 2024-11-23 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0008_favoris'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sujet',
            name='produit',
        ),
        migrations.AddField(
            model_name='sujet',
            name='categorie',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sujets', to='forum.categorie'),
            preserve_default=False,
        ),
    ]
