# Generated by Django 5.1.2 on 2024-11-23 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0009_remove_sujet_produit_sujet_categorie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avis',
            name='produit',
        ),
        migrations.AddField(
            model_name='avis',
            name='categorie',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='avis', to='forum.categorie'),
            preserve_default=False,
        ),
    ]
