# Generated by Django 5.1.2 on 2024-12-22 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0011_alter_sujet_utilisateur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sujet',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.utilisateur'),
        ),
    ]
